// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	langchain "github.com/JoshuaPangaribuan/dbot/internal/pkg/langchain"
	mock "github.com/stretchr/testify/mock"
)

// MockVectorStore is an autogenerated mock type for the VectorStore type
type MockVectorStore struct {
	mock.Mock
}

type MockVectorStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVectorStore) EXPECT() *MockVectorStore_Expecter {
	return &MockVectorStore_Expecter{mock: &_m.Mock}
}

// AddDocuments provides a mock function with given fields: ctx, docs
func (_m *MockVectorStore) AddDocuments(ctx context.Context, docs []langchain.Document) error {
	ret := _m.Called(ctx, docs)

	if len(ret) == 0 {
		panic("no return value specified for AddDocuments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []langchain.Document) error); ok {
		r0 = rf(ctx, docs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVectorStore_AddDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDocuments'
type MockVectorStore_AddDocuments_Call struct {
	*mock.Call
}

// AddDocuments is a helper method to define mock.On call
//   - ctx context.Context
//   - docs []langchain.Document
func (_e *MockVectorStore_Expecter) AddDocuments(ctx interface{}, docs interface{}) *MockVectorStore_AddDocuments_Call {
	return &MockVectorStore_AddDocuments_Call{Call: _e.mock.On("AddDocuments", ctx, docs)}
}

func (_c *MockVectorStore_AddDocuments_Call) Run(run func(ctx context.Context, docs []langchain.Document)) *MockVectorStore_AddDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]langchain.Document))
	})
	return _c
}

func (_c *MockVectorStore_AddDocuments_Call) Return(_a0 error) *MockVectorStore_AddDocuments_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVectorStore_AddDocuments_Call) RunAndReturn(run func(context.Context, []langchain.Document) error) *MockVectorStore_AddDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// SimilaritySearch provides a mock function with given fields: ctx, query, k
func (_m *MockVectorStore) SimilaritySearch(ctx context.Context, query string, k int) ([]langchain.Document, error) {
	ret := _m.Called(ctx, query, k)

	if len(ret) == 0 {
		panic("no return value specified for SimilaritySearch")
	}

	var r0 []langchain.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]langchain.Document, error)); ok {
		return rf(ctx, query, k)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []langchain.Document); ok {
		r0 = rf(ctx, query, k)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]langchain.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, query, k)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVectorStore_SimilaritySearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SimilaritySearch'
type MockVectorStore_SimilaritySearch_Call struct {
	*mock.Call
}

// SimilaritySearch is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - k int
func (_e *MockVectorStore_Expecter) SimilaritySearch(ctx interface{}, query interface{}, k interface{}) *MockVectorStore_SimilaritySearch_Call {
	return &MockVectorStore_SimilaritySearch_Call{Call: _e.mock.On("SimilaritySearch", ctx, query, k)}
}

func (_c *MockVectorStore_SimilaritySearch_Call) Run(run func(ctx context.Context, query string, k int)) *MockVectorStore_SimilaritySearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockVectorStore_SimilaritySearch_Call) Return(_a0 []langchain.Document, _a1 error) *MockVectorStore_SimilaritySearch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVectorStore_SimilaritySearch_Call) RunAndReturn(run func(context.Context, string, int) ([]langchain.Document, error)) *MockVectorStore_SimilaritySearch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVectorStore creates a new instance of MockVectorStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVectorStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVectorStore {
	mock := &MockVectorStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
