// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	discord "github.com/JoshuaPangaribuan/dbot/internal/pkg/discord"

	mock "github.com/stretchr/testify/mock"
)

// MockEventPermissionChecker is an autogenerated mock type for the EventPermissionChecker type
type MockEventPermissionChecker struct {
	mock.Mock
}

type MockEventPermissionChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPermissionChecker) EXPECT() *MockEventPermissionChecker_Expecter {
	return &MockEventPermissionChecker_Expecter{mock: &_m.Mock}
}

// HasPermissionForEvent provides a mock function with given fields: ctx, e, permission
func (_m *MockEventPermissionChecker) HasPermissionForEvent(ctx context.Context, e *discord.Event, permission string) bool {
	ret := _m.Called(ctx, e, permission)

	if len(ret) == 0 {
		panic("no return value specified for HasPermissionForEvent")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *discord.Event, string) bool); ok {
		r0 = rf(ctx, e, permission)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockEventPermissionChecker_HasPermissionForEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasPermissionForEvent'
type MockEventPermissionChecker_HasPermissionForEvent_Call struct {
	*mock.Call
}

// HasPermissionForEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - e *discord.Event
//   - permission string
func (_e *MockEventPermissionChecker_Expecter) HasPermissionForEvent(ctx interface{}, e interface{}, permission interface{}) *MockEventPermissionChecker_HasPermissionForEvent_Call {
	return &MockEventPermissionChecker_HasPermissionForEvent_Call{Call: _e.mock.On("HasPermissionForEvent", ctx, e, permission)}
}

func (_c *MockEventPermissionChecker_HasPermissionForEvent_Call) Run(run func(ctx context.Context, e *discord.Event, permission string)) *MockEventPermissionChecker_HasPermissionForEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*discord.Event), args[2].(string))
	})
	return _c
}

func (_c *MockEventPermissionChecker_HasPermissionForEvent_Call) Return(_a0 bool) *MockEventPermissionChecker_HasPermissionForEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPermissionChecker_HasPermissionForEvent_Call) RunAndReturn(run func(context.Context, *discord.Event, string) bool) *MockEventPermissionChecker_HasPermissionForEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventPermissionChecker creates a new instance of MockEventPermissionChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPermissionChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPermissionChecker {
	mock := &MockEventPermissionChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
