// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	discord "github.com/JoshuaPangaribuan/dbot/internal/pkg/discord"
	mock "github.com/stretchr/testify/mock"
)

// MockFeature is an autogenerated mock type for the Feature type
type MockFeature struct {
	mock.Mock
}

type MockFeature_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeature) EXPECT() *MockFeature_Expecter {
	return &MockFeature_Expecter{mock: &_m.Mock}
}

// Init provides a mock function with given fields: b
func (_m *MockFeature) Init(b *discord.Bot) error {
	ret := _m.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*discord.Bot) error); ok {
		r0 = rf(b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFeature_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockFeature_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - b *discord.Bot
func (_e *MockFeature_Expecter) Init(b interface{}) *MockFeature_Init_Call {
	return &MockFeature_Init_Call{Call: _e.mock.On("Init", b)}
}

func (_c *MockFeature_Init_Call) Run(run func(b *discord.Bot)) *MockFeature_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*discord.Bot))
	})
	return _c
}

func (_c *MockFeature_Init_Call) Return(_a0 error) *MockFeature_Init_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeature_Init_Call) RunAndReturn(run func(*discord.Bot) error) *MockFeature_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockFeature) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockFeature_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockFeature_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockFeature_Expecter) Name() *MockFeature_Name_Call {
	return &MockFeature_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockFeature_Name_Call) Run(run func()) *MockFeature_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFeature_Name_Call) Return(_a0 string) *MockFeature_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeature_Name_Call) RunAndReturn(run func() string) *MockFeature_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockFeature) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFeature_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockFeature_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFeature_Expecter) Shutdown(ctx interface{}) *MockFeature_Shutdown_Call {
	return &MockFeature_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockFeature_Shutdown_Call) Run(run func(ctx context.Context)) *MockFeature_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFeature_Shutdown_Call) Return(_a0 error) *MockFeature_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeature_Shutdown_Call) RunAndReturn(run func(context.Context) error) *MockFeature_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// Subscriptions provides a mock function with no fields
func (_m *MockFeature) Subscriptions() []*discord.Subscription {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subscriptions")
	}

	var r0 []*discord.Subscription
	if rf, ok := ret.Get(0).(func() []*discord.Subscription); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*discord.Subscription)
		}
	}

	return r0
}

// MockFeature_Subscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscriptions'
type MockFeature_Subscriptions_Call struct {
	*mock.Call
}

// Subscriptions is a helper method to define mock.On call
func (_e *MockFeature_Expecter) Subscriptions() *MockFeature_Subscriptions_Call {
	return &MockFeature_Subscriptions_Call{Call: _e.mock.On("Subscriptions")}
}

func (_c *MockFeature_Subscriptions_Call) Run(run func()) *MockFeature_Subscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFeature_Subscriptions_Call) Return(_a0 []*discord.Subscription) *MockFeature_Subscriptions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeature_Subscriptions_Call) RunAndReturn(run func() []*discord.Subscription) *MockFeature_Subscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFeature creates a new instance of MockFeature. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeature(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeature {
	mock := &MockFeature{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
