// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	discord "github.com/JoshuaPangaribuan/dbot/internal/pkg/discord"
	mock "github.com/stretchr/testify/mock"
)

// MockCommandProvider is an autogenerated mock type for the CommandProvider type
type MockCommandProvider struct {
	mock.Mock
}

type MockCommandProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandProvider) EXPECT() *MockCommandProvider_Expecter {
	return &MockCommandProvider_Expecter{mock: &_m.Mock}
}

// Commands provides a mock function with no fields
func (_m *MockCommandProvider) Commands() []*discord.Command {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commands")
	}

	var r0 []*discord.Command
	if rf, ok := ret.Get(0).(func() []*discord.Command); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*discord.Command)
		}
	}

	return r0
}

// MockCommandProvider_Commands_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commands'
type MockCommandProvider_Commands_Call struct {
	*mock.Call
}

// Commands is a helper method to define mock.On call
func (_e *MockCommandProvider_Expecter) Commands() *MockCommandProvider_Commands_Call {
	return &MockCommandProvider_Commands_Call{Call: _e.mock.On("Commands")}
}

func (_c *MockCommandProvider_Commands_Call) Run(run func()) *MockCommandProvider_Commands_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommandProvider_Commands_Call) Return(_a0 []*discord.Command) *MockCommandProvider_Commands_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandProvider_Commands_Call) RunAndReturn(run func() []*discord.Command) *MockCommandProvider_Commands_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommandProvider creates a new instance of MockCommandProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandProvider {
	mock := &MockCommandProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
