// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AwardXP provides a mock function with given fields: ctx, userID
func (_m *MockService) AwardXP(ctx context.Context, userID string) (int, int) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for AwardXP")
	}

	var r0 int
	var r1 int
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, int)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// MockService_AwardXP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AwardXP'
type MockService_AwardXP_Call struct {
	*mock.Call
}

// AwardXP is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockService_Expecter) AwardXP(ctx interface{}, userID interface{}) *MockService_AwardXP_Call {
	return &MockService_AwardXP_Call{Call: _e.mock.On("AwardXP", ctx, userID)}
}

func (_c *MockService_AwardXP_Call) Run(run func(ctx context.Context, userID string)) *MockService_AwardXP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_AwardXP_Call) Return(oldLevel int, newLevel int) *MockService_AwardXP_Call {
	_c.Call.Return(oldLevel, newLevel)
	return _c
}

func (_c *MockService_AwardXP_Call) RunAndReturn(run func(context.Context, string) (int, int)) *MockService_AwardXP_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function with given fields: ctx
func (_m *MockService) GetAllUsers(ctx context.Context) map[string]int {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 map[string]int
	if rf, ok := ret.Get(0).(func(context.Context) map[string]int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	return r0
}

// MockService_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockService_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetAllUsers(ctx interface{}) *MockService_GetAllUsers_Call {
	return &MockService_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx)}
}

func (_c *MockService_GetAllUsers_Call) Run(run func(ctx context.Context)) *MockService_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetAllUsers_Call) Return(_a0 map[string]int) *MockService_GetAllUsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_GetAllUsers_Call) RunAndReturn(run func(context.Context) map[string]int) *MockService_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetLevelForXP provides a mock function with given fields: ctx, xp
func (_m *MockService) GetLevelForXP(ctx context.Context, xp int) int {
	ret := _m.Called(ctx, xp)

	if len(ret) == 0 {
		panic("no return value specified for GetLevelForXP")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, xp)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockService_GetLevelForXP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLevelForXP'
type MockService_GetLevelForXP_Call struct {
	*mock.Call
}

// GetLevelForXP is a helper method to define mock.On call
//   - ctx context.Context
//   - xp int
func (_e *MockService_Expecter) GetLevelForXP(ctx interface{}, xp interface{}) *MockService_GetLevelForXP_Call {
	return &MockService_GetLevelForXP_Call{Call: _e.mock.On("GetLevelForXP", ctx, xp)}
}

func (_c *MockService_GetLevelForXP_Call) Run(run func(ctx context.Context, xp int)) *MockService_GetLevelForXP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockService_GetLevelForXP_Call) Return(_a0 int) *MockService_GetLevelForXP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_GetLevelForXP_Call) RunAndReturn(run func(context.Context, int) int) *MockService_GetLevelForXP_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextThreshold provides a mock function with given fields: ctx, level
func (_m *MockService) GetNextThreshold(ctx context.Context, level int) int {
	ret := _m.Called(ctx, level)

	if len(ret) == 0 {
		panic("no return value specified for GetNextThreshold")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, level)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockService_GetNextThreshold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextThreshold'
type MockService_GetNextThreshold_Call struct {
	*mock.Call
}

// GetNextThreshold is a helper method to define mock.On call
//   - ctx context.Context
//   - level int
func (_e *MockService_Expecter) GetNextThreshold(ctx interface{}, level interface{}) *MockService_GetNextThreshold_Call {
	return &MockService_GetNextThreshold_Call{Call: _e.mock.On("GetNextThreshold", ctx, level)}
}

func (_c *MockService_GetNextThreshold_Call) Run(run func(ctx context.Context, level int)) *MockService_GetNextThreshold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockService_GetNextThreshold_Call) Return(_a0 int) *MockService_GetNextThreshold_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_GetNextThreshold_Call) RunAndReturn(run func(context.Context, int) int) *MockService_GetNextThreshold_Call {
	_c.Call.Return(run)
	return _c
}

// GetXP provides a mock function with given fields: ctx, userID
func (_m *MockService) GetXP(ctx context.Context, userID string) int {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetXP")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockService_GetXP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetXP'
type MockService_GetXP_Call struct {
	*mock.Call
}

// GetXP is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockService_Expecter) GetXP(ctx interface{}, userID interface{}) *MockService_GetXP_Call {
	return &MockService_GetXP_Call{Call: _e.mock.On("GetXP", ctx, userID)}
}

func (_c *MockService_GetXP_Call) Run(run func(ctx context.Context, userID string)) *MockService_GetXP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetXP_Call) Return(_a0 int) *MockService_GetXP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_GetXP_Call) RunAndReturn(run func(context.Context, string) int) *MockService_GetXP_Call {
	_c.Call.Return(run)
	return _c
}

// SetXP provides a mock function with given fields: ctx, userID, xp
func (_m *MockService) SetXP(ctx context.Context, userID string, xp int) {
	_m.Called(ctx, userID, xp)
}

// MockService_SetXP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetXP'
type MockService_SetXP_Call struct {
	*mock.Call
}

// SetXP is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - xp int
func (_e *MockService_Expecter) SetXP(ctx interface{}, userID interface{}, xp interface{}) *MockService_SetXP_Call {
	return &MockService_SetXP_Call{Call: _e.mock.On("SetXP", ctx, userID, xp)}
}

func (_c *MockService_SetXP_Call) Run(run func(ctx context.Context, userID string, xp int)) *MockService_SetXP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockService_SetXP_Call) Return() *MockService_SetXP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_SetXP_Call) RunAndReturn(run func(context.Context, string, int)) *MockService_SetXP_Call {
	_c.Run(run)
	return _c
}

// UserCount provides a mock function with given fields: ctx
func (_m *MockService) UserCount(ctx context.Context) int {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UserCount")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockService_UserCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserCount'
type MockService_UserCount_Call struct {
	*mock.Call
}

// UserCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) UserCount(ctx interface{}) *MockService_UserCount_Call {
	return &MockService_UserCount_Call{Call: _e.mock.On("UserCount", ctx)}
}

func (_c *MockService_UserCount_Call) Run(run func(ctx context.Context)) *MockService_UserCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_UserCount_Call) Return(_a0 int) *MockService_UserCount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_UserCount_Call) RunAndReturn(run func(context.Context) int) *MockService_UserCount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
